export const getData = () => {
  const data = {
    "pokemon" : [
      {
        "name": "Charizard",
        "picture": "https://pokestop.io/img/pokemon/charizard-128x128.png",
        "id": "6",
        "weight": "90.5",
        "height": "170",
        "stats": [
          {"hp" : 78},
          {"attack" : 84},
          {"speed" : 100},
          {"defense" : 78},
          {"special-attack" : 109},
          {"special-defense" : 85},
        ],
        "types": [ "fire", "flying" ],
      },
      {
        "name": "Clefairy",
        "picture": "https://pokestop.io/img/pokemon/clefairy-128x128.png",
        "id": "35",
        "weight": "7.5",
        "height": "60",
        "stats": [
          {"hp" : 70},
          {"attack" : 45},
          {"speed" : 35},
          {"defense" : 48},
          {"special-attack" : 60},
          {"special-defense" : 65},
        ],
        "types": [ "fairy" ],
      },
      {
        "name": "Abra",
        "picture": "https://pokestop.io/img/pokemon/abra-128x128.png",
        "id": "63",
        "weight": "19.5",
        "height": "90",
        "stats": [
          {"hp" : 25},
          {"attack" : 20},
          {"speed" : 90},
          {"defense" : 15},
          {"special-attack" : 105},
          {"special-defense" : 55},
        ],
        "types": [ "psychic" ],
      },
      {
        "name": "Kadabra",
        "picture": "https://pokestop.io/img/pokemon/kadabra-128x128.png",
        "id": "64",
        "weight": "56.5",
        "height": "130",
        "stats": [
          {"hp" : 40},
          {"attack" : 35},
          {"speed" : 105},
          {"defense" : 30},
          {"special-attack" : 120},
          {"special-defense" : 70},
        ],
        "types": [ "psychic" ],
      },
      {
        "name": "Gengar",
        "picture": "https://pokestop.io/img/pokemon/gengar-128x128.png",
        "id": "94",
        "weight": "40.5",
        "height": "150",
        "stats": [
          {"hp" : 60},
          {"attack" : 65},
          {"speed" : 110},
          {"defense" : 60},
          {"special-attack" : 130},
          {"special-defense" : 75},
        ],
        "types": [ "ghost", "poison" ],
      },
      {
        "name": "Mr. Mime",
        "picture": "https://pokestop.io/img/pokemon/mr-mime-128x128.png",
        "id": "122",
        "weight": "54.5",
        "height": "130",
        "stats": [
          {"hp" : 40},
          {"attack" : 45},
          {"speed" : 90},
          {"defense" : 65},
          {"special-attack" : 100},
          {"special-defense" : 120},
        ],
        "types": [ "psychic", "fairy" ],
      },
      {
        "name": "Ditto",
        "picture": "https://pokestop.io/img/pokemon/ditto-128x128.png",
        "id": "132",
        "weight": "4",
        "height": "30",
        "stats": [
          {"hp" : 48},
          {"attack" : 48},
          {"speed" : 48},
          {"defense" : 48},
          {"special-attack" : 48},
          {"special-defense" : 48},
        ],
        "types": [ "normal" ],
      },
      {
        "name": "Eevee",
        "picture": "https://pokestop.io/img/pokemon/eevee-128x128.png",
        "id": "133",
        "weight": "6.5",
        "height": "30",
        "stats": [
          {"hp" : 55},
          {"attack" : 55},
          {"speed" : 55},
          {"defense" : 50},
          {"special-attack" : 45},
          {"special-defense" : 65},
        ],
        "types": [ "normal" ],
      },
      {
        "name": "Porygon",
        "picture": "https://pokestop.io/img/pokemon/porygon-128x128.png",
        "id": "137",
        "weight": "36.5",
        "height": "80",
        "stats": [
          {"hp" : 65},
          {"attack" : 60},
          {"speed" : 40},
          {"defense" : 70},
          {"special-attack" : 85},
          {"special-defense" : 75},
        ],
        "types": [ "normal" ],
      },
      {
        "name": "Articuno",
        "picture": "https://pokestop.io/img/pokemon/articuno-128x128.png",
        "id": "144",
        "weight": "55.4",
        "height": "170",
        "stats": [
          {"hp" : 90},
          {"attack" : 85},
          {"speed" : 85},
          {"defense" : 100},
          {"special-attack" : 95},
          {"special-defense" : 125},
        ],
        "types": [ "ice", "flying"],
      },

    ]
  }

  return data;
}